######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 4 20:51:16 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h
SOURCES += imageviewer.cpp main.cpp
